### ISSUE TITLE
Piece-square tables: find tables to use or make our own?

### ISSUE THREAD

**Issue by ZirconiumX** [japanoise/kusanagi#10]
I used Adam Hair's tables, but we can maybe make our own?

**Comment by ZirconiumX** [comment]
@japanoise: I think this should be a must, since the engine plays very poorly without any form of positional knowledge.

**Comment by japanoise** [comment]
Highlighted as top priority.

**Comment by japanoise** [comment]
Tables from http://talkchess.com/forum/viewtopic.php?t=50840&postdays=0&postorder=asc&highlight=pst+challenge&topic_view=flat&start=20 added in acf148d002a42c6286c21d8347da15e2d680b9e8

**Comment by japanoise** [comment]
first phase of implementation in 108fe3b53922842aa0a4aca33a65c0f1826bb23c but need game phase #11 to close

**Comment by japanoise** [comment]
Implemented with tapered eval.
