### ISSUE TITLE
Game phase

### ISSUE THREAD

**Issue by ZirconiumX** [japanoise/kusanagi#11]
Not too hard to implement Fruit-style.

**Comment by japanoise** [comment]
Should; pending investigation on whether it's easy enough to switch to Must.

**Comment by ZirconiumX** [comment]
Fruit implements it like this:
```
N/B phase value = 1
R phase value = 2
Q phase value = 4
```
- You start with a counter - `phase` - initialised to `2*Q+4*R+4*B+4*N` (call this number `StartPhase` or whatever).
- You scan through each piece, and subtract its phase value from phase, and update an opening/endgame value as necessary.

At the end of the eval, you crossfade between opening and endgame using phase as the interpolation value, roughly like this:

```
score = ((opening * phase) + (endgame * (StartPhase - phase)) / StartPhase
```

(I hope I got the math right...)

**Comment by japanoise** [comment]
Is blocking #10

**Comment by japanoise** [comment]
Implemented in 1afecdda642fcfec1473a8a8c5f92575662c2168 
@ZirconiumX to test

**Comment by ZirconiumX** [comment]
Testing blocked on #39.

**Comment by japanoise** [comment]
@ZirconiumX - ready to close?
