### ISSUE TITLE
Move Ordering: MVV/LVA capture ordering

### ISSUE THREAD

**Issue by ZirconiumX** [japanoise/kusanagi#20]
Cheap and nasty.

**Comment by ZirconiumX** [comment]
In d52e8cca and e0808a19. ~400 elo!

**Comment by japanoise** [comment]
e0808a1900d2d7d24185034b5523366d03d67962 and d52e8cca51acbf8acdfa12b22fd2195490a07b9e

**Comment by ZirconiumX** [comment]
JINX!
