### ISSUE TITLE
Quiescence Search

### ISSUE THREAD

**Issue by ZirconiumX** [japanoise/kusanagi#32]
Essentially capture-only alpha-beta, with the option of doing nothing.

To not be crap, we need MVV/LVA.

Requires:
- #20 
- #33

**Comment by ZirconiumX** [comment]
I have this in my unpushed tree - should I test this for elo @japanoise?

I think it would be a good precedent at least.

**Comment by japanoise** [comment]
Sure sure.

**Comment by ZirconiumX** [comment]
Committed in 0297c9b, so closing.
